### ISSUE TITLE
Renaming this organization

### ISSUE THREAD

**Issue by renzok** [GenomicsStandardsConsortium/mixs#12]
Hi @GenomicsStandardsConsortium/mixs-dev ,

we have to rename https://github.com/GenomicsStandardsConsortium 
 because it is simply wrong. The correct name of GSC is  Genomic (without s) Standards Consortium.

I suggest to vote between:

1. genomicstandardsconsortium
2. genomic-standards-consortium
2. gensc

Please add your vote as comments to this issue. 

Once we agreed on a new name, I will continue to rename this according to
https://help.github.com/articles/renaming-an-organization/

- [ ] Finish voting 
- [ ] Rename this organization according to majority vote

**Comment by genomicstandardsconsortium** [comment]
Hello Renzo,
    I would go with

  1.  genomic-standards-consortium

For the name of the GitHub repository.

Cheers,
Lynn

Lynn M. Schriml, Ph.D.
Associate Professor
Institute for Genome Sciences
University of Maryland
School of Medicine
Department of Epidemiology and Public Health
801 W. Baltimore St., Room 659
Baltimore, MD 21201
P: 410-706-6776
F: 410-706-6756
lschriml@som.umaryland.edu<mailto:lschriml@som.umaryland.edu>



On Nov 3, 2017, at 1:46 PM, renzo <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @GenomicsStandardsConsortium/mixs-dev<https://github.com/orgs/GenomicsStandardsConsortium/teams/mixs-dev> ,

we have to rename https://github.com/GenomicsStandardsConsortium
because it is simply wrong. The correct name of GSC is Genomic (without s) Standards Consortium.

I suggest to vote between:

  1.  genomicstandardsconsortium
  2.  genomic-standards-consortium
  3.  gensc

Please add your vote as comments to this issue.

Once we agreed on a new name, I will continue to rename this according to
https://help.github.com/articles/renaming-an-organization/

  *    Finish voting
  *    Rename this organization according to majority vote

**Comment by genomicstandardsconsortium** [comment]
I have no strong preference between the two full name choices.

Granger Sutton, Ph.D.
Professor, Informatics
J. Craig Venter Institute
9714 Medical Center Drive
Rockville, MD 20850
301-795-7392

**Comment by genomicstandardsconsortium** [comment]
Hello Renzo,
Have you received feedback ?
It would be great to get this finalized.

Cheers,
Lynn


On Nov 6, 2017, at 11:57 AM, Sutton, Granger <gsutton@jcvi.org<mailto:gsutton@jcvi.org>> wrote:

I have no strong preference between the two full name choices.

Granger Sutton, Ph.D.
Professor, Informatics
J. Craig Venter Institute
9714 Medical Center Drive
Rockville, MD 20850
301-795-7392

**Comment by folker** [comment]
Hi all,

gensc.org is a terrible name (IMO inspired by not understanding the fact that nobody types domain names and everyone uses google searches to find things). It comes from a dark (past) age when folks where looking for short domain names. that era has passed.

we should not duplicate that mistake. lets remove the superfluous “s” and get on with it. I think we should change the name of the repo soonish before too many folks are affected.

just my $0.02

best,
Folker

**Comment by folker** [comment]
closing for now.
