### ISSUE TITLE
route of transmission - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#173]
**New term details**
```
Term name - route of transmission
Structured comment name - route_transmission
Definition - Description of symbiont specific path taken using the chosen mode to establish the association.
Expected value - enumeration
Value syntax - [environmental:faecal-oral|transplacental|vector-borne:vector penetration]
Example - 
Packages(s) - symbiont-assiociated
Already assigned MIXS ID - MIXS:0001316
```

**Additional context**
Term created as part of Symbiont associated package.

**Comment by pbuttigieg** [comment]
Discussed in CIG call:

Definition clean-up: removing circularity, clarifying dependence on mode_transmission, working around ambiguous use of "symbiont" #

```
Term name - route of transmission
Structured comment name - route_transmission
Definition - Description of path taken by an organism in order to establish a symbiotic relationship with another via a mode of transmission (specified in mode_transmission).
Expected value - enumeration
Value syntax - [environmental:faecal-oral|transplacental|vector-borne:vector penetration]
Example - 
Packages(s) - symbiont-assiociated
Already assigned MIXS ID - MIXS:0001316
```

**Comment by ramonawalls** [comment]
Updated spreadsheet.

**Comment by only1chunts** [comment]
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)

**Comment by ndheilly** [comment]
The way the host being sampled is referenced to in definitions Kereps changing. 
For consistency, the definition needs to be modofied as follow:

Term name - route of transmission
Structured comment name - route_transmission
Definition - Description of path taken by the symbiotic host organism in order to establish a symbiotic relationship with another organism via a mode of transmission (specified in mode_transmission).
Expected value - enumeration
Value syntax - [environmental:faecal-oral|transplacental|vector-borne:vector penetration]
Example - 
Packages(s) - symbiont-assiociated
Already assigned MIXS ID - MIXS:0001316

**Comment by ndheilly** [comment]
One additional small change required in order to use exactly the same phrasing as in mode of transmission:

Term name - route of transmission
Structured comment name - route_transmission
Definition - Description of path taken by the symbiotic host organism in order to establish a symbiotic relationship with the host from which it was sampled via a mode of transmission (specified in mode_transmission).
Expected value - enumeration
Value syntax - [environmental:faecal-oral|transplacental|vector-borne:vector penetration]
Example -
Packages(s) - symbiont-assiociated
Already assigned MIXS ID - MIXS:0001316

**Comment by only1chunts** [comment]
Updated definition to:

Description of path taken by the symbiotic host organism being sampled in order to establish a symbiotic relationship with the host (with which it was observed at the time of sampling) via a mode of transmission (specified in mode_transmission).

**Comment by ndheilly** [comment]
Ok
