### ISSUE TITLE
specify domains for MIxS properties

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#241]
If, as per GenomicsStandardsConsortium/mixs-rdf#9, we are using RDF properties for MIxS attributes, we should decide whether or not to specify [domains](https://www.w3.org/2001/sw/RDFCore/Schema/20010618/#s3.1.4) for some or all of those properties.

**Comment by ramonawalls** [comment]
Issue no longer relevant.

**Comment by turbomam** [comment]
I would like to briefly discuss the meaning of "no longer relevant" on 2024-01-02 if possible

**Comment by turbomam** [comment]
MIxS is (intentionally?) vague about domain. Since `MimsSoil` uses the `depth` slot, `MimsSoil` is in the domain of `depth`

But if a user is filling out the `MimsSoil` metadata collection template, what is each row? @mslarae13 made the reasonable suggestion that is a DNA sample that happens to come from soil.
