### ISSUE TITLE
Content negotiation for MIxS landing pages

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#246]
Landing pages will be generated using NMDC code to create pages like https://microbiomedata.github.io/nmdc-metadata/docs/tot_depth_water_col.html that resolve to the gensc website. Would be great to have content negotiation to deliver machine readable pages as well. 

Not currently in Biolink ML library. Maybe we can get @jdeck88 to add some code for this.

**Comment by only1chunts** [comment]
At the moment I'm using a file called terms.yml in the _data directory of the website repo ([here](https://github.com/GenomicsStandardsConsortium/gensc.github.io/blob/main/_data/terms.yml)).  I'm happy to change things as this was just me playing around to see what could be done.
All that it does at the moment is create a single page with all the terms: https://genomicsstandardsconsortium.github.io/gensc.github.io/pages/standards/all-terms.html
and allow a search over the terms:
https://genomicsstandardsconsortium.github.io/gensc.github.io/pages/standards/search-terms.html

Maybe writing user stories will help define what is needed and how to provide it?
As a website user
I want to be able to see all the possible pre-defined checklists ratified by the GSC
So that I can choose the most appropriate one for my work

As I website user
I want to be able to search all current terms defined by the GSC
So that I can easily find definitions of a particular term
And see which packages it is part of.

As a website user
I want to be able to download an Excel (or other tabular format) file for any given Checklist with any given package 
So that I can use it for my work

As a website user
I want to be able to create my own adhoc package from the mandatory terms of a checklist and addition of any terms I select from the full list of available terms
So that I can create a bespoke checklist for my work that is still compliant with the core MIxS standards

**Comment by ramonawalls** [comment]
Great idea, Chris.

**Comment by cmungall** [comment]
Hi Chris - can we talk about this next CIG meeting? It seems this is maybe
duplicative with the linkml yaml?

**Comment by cmungall** [comment]
Would be awesome to have John's help!

I need to check the status of conneg. We have the rules defined for the
metamodel itself
https://github.com/perma-id/w3id.org/blob/master/linkml/.htaccess but not
easy how it is to set this up

**Comment by ramonawalls** [comment]
I think we have two overlapping issues here: one for content negotiation (html versus rdf) and one for handling pacakges. We should probably open a new ticket for managing packages, if one does not exist.

**Comment by ramonawalls** [comment]
What we want is for each term (and package?) page to offer different content depending on who accesses it. For humans, go to web page, for machines, return WHAT? Probably JSON-LD. Maybe RDF.

LinkML does not currently have a standard mechanism for creating the machine readable content for individual terms. **Need to file an issue with LinkML**

**Comment by cmungall** [comment]
I think step 1 is having the URIs resolve!

I assume we want URLs with human readable names as well as numeric IDs to resolve?

**Comment by turbomam** [comment]
Issue #391 advocates for numeric-only URLs

**Comment by ramonawalls** [comment]
> I think step 1 is having the URIs resolve!
Yes! We have issues #390  and #391 for this, and @sujaypatil96 is working on it.
> 
> I assume we want URLs with human readable names as well as numeric IDs to resolve?
Our plan is for numerical URLs? What would be the added advantage of having human readable URLs, @cmungall ? It seems unwise to have two URLs per term.

**Comment by turbomam** [comment]
We currently support navigating to term pages like http://w3id.org/mixs/0000002, to the schema source via http://w3id.org/mixs/mixs.yaml, and to selected artifacts derived from the schema like http://w3id.org/mixs/mixs.owl.ttl and http://w3id.org/mixs/mixs/schema.json

When I think of content negotiation, I think of

1. some agent passing a desired MIME  file type
2. the host possibly returning something computable and atomic, like RDF for just one term

I don't believe LinkML has any support for 2., although we might be able to suport it though a triple store server

Does this require further discussion?

**Comment by cmungall** [comment]
We have an upstream issue that discusses how this would work.

- https://github.com/linkml/linkml/issues/686

As far as I know there is no one in either the GSC community or the more general standards/linkml community who would use this feature. It's something people on the semantic web community were very keen on 10 years ago. Note in the OBO community most major ontologies no longer support content negotiation.

I suggest either closing this issue, with the option of reopening if someone has need for it and resources to support. But fine if people want to leave it open. Keep discussion on the upstream ticket unless there are MIxS-specific requirements

**Comment by ramonawalls** [comment]
Issue solved with mixs 6.0-6.2 releases.

**Comment by turbomam** [comment]
I would like to briefly discuss the meaning of "issue solved" on 2024-01-02 if possible

**Comment by turbomam** [comment]
We aren't really doing content negotiation, but there are good 

https://en.wikipedia.org/wiki/Content_negotiation
