### ISSUE TITLE
Fix overspecification of parameter definitions

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#34]
CC @jzrapp

For example, "porosity" applies to more than just soil (sediment, sea ice). We should relabel or remove overspecified parameters on detection.

Copy of GenomicsStandardsConsortium/mixs-ng#8 originally filed by @pbuttigieg

**Comment by ramonawalls** [comment]
Replaced by #39

**Comment by ramonawalls** [comment]
In fact, this is not a duplication to issue #39. Instead, this issue has to do with having terms in different checklists that have different labels, but should possibly be merged into a singe term.

I have copied @jzrapp 's comment from #34 here for clarification:

Some of the packages contain terms for which very specific definitions have been provided. However, the term itself may also be applicable to a different environment, but the specificity of the definition encourages duplication of terms, with slight modifications to the definition. A more coherent solution could be the establishment of overarching packages for e.g. physical characteristics of sample, or biological description of sample

Examples of such terms include:
"permeability" from hydrocarbon resources-cores package
"bacterial production" from water package
"bacterial respiration" from water package
"horizon" from soil package

**Comment by msweetlove** [comment]
I went through the list of terms in the packages (the v6 working version), and found these ones that could be defined more broadly (with a suggested new definition):
This list is probably not exhaustive

**term =** permeability
**termID =** MIXS:0000404
**definition =** Measure of the ability of material (such as a hydrocarbon resource or a membrane) to allow fluids to pass through it. 

**term =** bac_prod
**termID =** MIXS:0000683
**definition =** A measure of microbial production in a sample or environment (e.g. measured by isotope uptake)

note: for the term bad_prod[MIXS:0000683], should the term name maybe be changed to microbial production or just production? Because the production of Archaea and eukaryote algae can also be measured. Or do we add new terms, such as Archaea production and Eukaryote production?

**term =** bac_resp
**termID =** MIXS:0000684
**definition =** A measure of microbial respiration in a sample or environment

note: same remark as bad_prod: what about other microbial groups?

**term =** horizon
**termID =** MIXS:0001082
**definition =** Specific layer in the soil or sediment that possesses physical characteristics which differ from the layers above and beneath

**term =** host_taxid
**termID =** MIXS:0000250
**definition =** the taxon id of the host according to a taxonomic backbone, for example NCBI (e.g. NCBI:txid2004416), WoRMS (urn:lsid:marinespecies.org:taxname:387241),... Note that the ID number also needs to mention the name of the taxonomic backbone.

**term =** lithology
**termID =** MIXS:0000990
**definition =** the main rock type. This differs from env_medium[MIXS:0000014] as it does not need be in direct contact with the sample.

note: what is the difference between lithology[MIXS: 0000990] and sr_lithology[MIXS: 0000995]?

**term =** samp_transport_cond
**termID =** MIXS:0000410
**definition =** Explain the conditions of the sample transport, such as the duration of the transport (in days or hrs), the temperature the sample was exposed to (degrees Celsius), light exposure,...

**Comment by only1chunts** [comment]
@msweetlove , Thanks for the list these are really useful. 
I'm going to create individual tickets for each of the terms you list and close this ticket. I may also suggest we leave some of the terms for review in v7 as we're rapidly running out of time for this v6 release.

**Comment by only1chunts** [comment]
all individual terms given their own tickets, except "horizon" as I feel the current definition is suitable for use in any of the packages.
