### ISSUE TITLE
What does it mean to have an Excel file of MIxS 6 for partners like NCBI?

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#365]
I think @ramonawalls said she needs to share a Microsoft Excel representation of MIxS 6 with NCBI.

I tried to generate the LinkML Excel artifact, but that is just a collection of sheets, each of which models one class and has column headers for that class' slots.

That Excel generation isn't working anyway #360 

Chris Mungall suggested using the new schema to schemasheets converter

**Comment by turbomam** [comment]
schema sheets export (incomplete)

**Comment by turbomam** [comment]
Is something equivalent in format to the MIxS 5 sheet required?

**Comment by ramonawalls** [comment]
Sorry for the delay. Been tied up in meetings since 5. Yes, what we need is an Excel workbook very similar to the MIxS4 and 5 releases. Two possible ways to generate it:

1. Use the CSV files that are created by LinkML and and manually create the workbook.
2.  Copy the sheets from google sheets and manually construct the workbook.

I think either one should be okay, but I am a little concerned about method 2 diverging from the LinkML artifacts.

**Comment by ramonawalls** [comment]
It was agreed by all on the CIG (including people from INSDC) that the TSV release files are adequate.
