### ISSUE TITLE
Is there a fast track for addressing issues? Who monitors issues and PRs?

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#398]
Sometimes I see an issue that seems import and/or easy enough that I'm tempted to just make a PR without any discussion. 

For example #397, "bad 'air particulate matter concentration' in addition to valid 'air_PM_concen'"

If I create a PR, what should I expect in terms of getting it reviewed and merged? Who is entitled to do that kind of thing? For example, could @sujaypatil96 and I merge one another's critical or minor PRs, or does it have to wait for one of the biweekly meetings?

Apologies to anyone I omitted from the "assignees" list

**Comment by lschriml** [comment]
Hello @turbomam Mark, 
If there is an urgent issue, Submit the ticket and email Ramona, Chris and I,
rather than a pull request. 

Cheers,
Lynn

**Comment by only1chunts** [comment]
I think most things need to be done through the monthly Task Group meetings, where there is more urgency then perhaps @ramona can approve minor things and just note them for comment in the next TG call.
With respect to the #397, some discussion is probably warranted with regards to what exactly needs to be changed, i.e. which slot gets deleted and what impact that has on the packages using each of those slots. So that to me sounds like something that needs to be brought up in the TG call.

**Comment by turbomam** [comment]
Sure, I wouldn't want to shortcut the discussion process

Unfortunately, some of the issues I have raised are related to broken functionality that effects NMDC.

**Comment by ramonawalls** [comment]
We have discussed this several times in the TWG calls. Our current plan is to aggregate issues in this project: https://github.com/orgs/GenomicsStandardsConsortium/projects/1/views/1
