### ISSUE TITLE
Definition for heavy_metals wrong

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#40]
In MIxS 4 and MIxS 5 the definition for `heavy_metals` reads:
```
Heavy metals present and concentrationsany drug used by subject and the frequency of usage; can include multiple heavy metals and concentrations
```
Can someone fix the "concentrationsany" part?

**Comment by josieburgin** [comment]
Hi @only1chunts and @ramonawalls, I'm happy to make this update but I'm not sure where this needs to be logged?
Thanks

**Comment by ramonawalls** [comment]
Since this term is in the soil package and refers to drugs used by the patient, I assume that a copy paste error occurred. I suggest the following change:

Current 

definition: Heavy metals present and concentrationsany drug used by subject and the frequency of usage; can include multiple heavy metals and concentrations

expected value: heavy metal name;measurement value

example: 

New 

definition: Heavy metals present in the sequenced sample and their concentrations. For multiple heavy metals and concentrations, and multiple copies of this field.

expected value (to match syntax): heavy metal name measurement value;unit

example: mercury;0.09 micrograms per gram

**Comment by ramonawalls** [comment]
Updated spreadsheet. Moving to review in progress.

**Comment by only1chunts** [comment]
added to change log
