### ISSUE TITLE
Replace Excel MIxS files with online documentation and TSV and Data Harmonizer 

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#407]
Most of the Excel files (for individual packages and checklists) can be replaced by TSVs. They have no special formatting. The multi-sheet Excel file that includes directions could be replaced by online documentation. The website will point to the TSVs for all checklist/package combinations. 

Discussed on the CIG call on 6/28/2022 and approved this change.

We will need code to generate the TSV files.

We should also create Data Harmonizer packages for all the packages and checklists.

**Comment by ramonawalls** [comment]
Files should be similar to those contained in https://github.com/GenomicsStandardsConsortium/mixs/tree/main/release/excel. 

There should be one file for each checklist, package, and each combination.

We need code to create the TSV files from the MIxS yaml source.

We do not need to create  mixs.xlsx.

Ideally, they Excel files should be available via the documentation. Links from website (not linkml documentation) could go to linkml documentation or to github file.

**Comment by sujaypatil96** [comment]
Can this issue be closed with the development work done to create Excel data collection templates here: https://github.com/GenomicsStandardsConsortium/mixs/tree/main/mixs-templates?

Instead of creating TSV files as originally requested in this issue, we are creating XLSX files because they have a feature that we can take advantage of documented https://github.com/GenomicsStandardsConsortium/mixs/tree/main/mixs-templates#mixs-metadata-collection-spreadsheet-templates and https://linkml.io/linkml/generators/excel.html

> Ideally, they Excel files should be available via the documentation. Links from website (not linkml documentation) could go to linkml documentation or to github file.
There is an issue that document the above. See https://github.com/GenomicsStandardsConsortium/mixs/issues/730

I think this issue can be closed.
