### ISSUE TITLE
Display columns in MkDocs pages of checklists and packages

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#408]
## User story
> As a website user
> I would like to see all the relevant details about the terms in a given package/checklist
> So that I can easily determine which terms are required vs recommended

## Acceptance criteria
> Given I have navigated to any Checklist-Package combination documentation page e.g. https://genomicsstandardsconsortium.github.io/mixs/BuiltEnvironmentMIGSEukaryote/
> When I look at the "Slots" table
> Then I can see columns for the following:
MIxS ID
Full Name
Requirement
Short Name
Definition
Value syntax
Expected value
Example
Preferred unit
Occurrence

## Additional information

NB the above wording is how these are shown in the old excel formatted versions of the tables, below I try to map those to the names used in the LinkML version:
Short Name = slot name
MIxS ID = slot_uri
Full Name = title
definition = description
Value Syntax = range
Occurence = multivalued
Example = examples
Expected value =  annotations:      expected_value: text
Requirement = ? I cant see this information stored in the terms.yaml file ?
Preferred unit = I'm not sure, but I think this is stored in the packages yamls somewhere under slot_usage maybe?

**Comment by sujaypatil96** [comment]
When I look at the "Slots" table
Then I can see columns for the following:

> MIxS ID ✅

> Full Name

Why do you want to see the _full name_ when the short name is linked out? you can simply click on the page for the slot (with short name) and read what the full name is

> Requirement

The cardinality captures the requiredness. See https://linkml.io/linkml/schemas/slots.html#cardinality page to learn how the cardinality syntax on the web documentation pages can be read/interpreted

> Short Name ✅

> Definition

Similar to full name, why would you want to see this when you can simply click on the documentation page for the slot and view the description. We should try to avoid cramming in information in tables because it has limited space on a web page and cramming in a lot of columns introduces horizontal scroll and that it is ideally undesired behavior

> Value syntax

I'm forgetting what this means?

> Expected value

I'm forgetting what this means?

> Example ✅ -- "Examples" section

> Preferred unit ✅ -- shown in "Range"

> Occurrence ✅ -- shown in "Applicable checklists and extensions" section

**Comment by sujaypatil96** [comment]
I think this issue can be closed @only1chunts?
