### ISSUE TITLE
Migration for plan for annual season temp/precipitation

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#41]
MIxS 4 has the terms `annual_season_temp` and `annual_season_precpt`.
In MIxS 5 these terms have been broken into the terms:
`annual_temp`  / `season_temp`
`annual_precpt` / `season_precpt`

Is there a migration plan for how to move values represented using the MIxS 4 terms to the corresponding MIxS 5 terms?

**Comment by cmungall** [comment]
Aside: We may want to consider SSSOM format to distribute mappings, including mappings between different versions https://github.com/OBOFoundry/SSSOM

This will allow us to specify exact vs non-exact mappings (using SKOS)

For this particular question, I assume it is the case that `season_X` terms should only be used if `season` is specified, otherwise it's hard to interpret the X?

**Comment by lschriml** [comment]
No current action items for this ticket.
