### ISSUE TITLE
remove release directory

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#424]
this has been obsoleted by `mixs/`, right?

**Comment by ramonawalls** [comment]
I thought that `release` was renamed to `mixs`, but i see not that release is still there. Yes, release needs to be removed. Let's make a branch for 6.1.1 and put all of the next changes there. I will make a project.

**Comment by raissameyer** [comment]
@turbomam @ramonawalls 

Due to the removal of the release folder, the links to MIxS v6 on the [GSC website](https://press3.mcs.anl.gov/gensc/mixs/) no longer resolve (see below). With editing access to the website, this should be a quick fix.

![image](https://user-images.githubusercontent.com/48056511/183415453-d8bf3887-7051-4bda-b629-183c03102b0d.png)

**Comment by turbomam** [comment]
Yeah, we haven't done a great job of synchronizing changes in URLs across the various MIxS and GSC resources

@raissameyer, are you requesting write access to the source of that website, so that you can offer a pull request? Or is your comment above meant an encouragement for us to do this ourselves? 

@only1chunts I recognize the content that @raissameyer linked to above, but I don't recognize the host part: https://press3.mcs.anl.gov/gensc/mixs/

**Comment by raissameyer** [comment]
@turbomam 
> @raissameyer, are you requesting write access to the source of that website, so that you can offer a pull request? Or is your comment above meant an encouragement for us to do this ourselves?

Sorry for the confusion. It was indeed meant as an encouragement.
