### ISSUE TITLE
rel_to_oxy vs oxy_stat_sample

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#440]
In specific packages (soil in what I was looking at)
oxy_stat_samp: Oxygenation status of sample | enumeration | [aerobic\|anaerobic]

In core
rel_to_oxygen: Is this organism an aerobe, anaerobe? Please note that aerobic and anaerobic are valid descriptors for microbial environments | enumeration | [aerobe\|anaerobe\|facultative\|microaerophilic\|microanaerobe\|obligate aerobe\|obligate anaerobe]

Because the same enumeration values are shared, it's unclear how they're different? Why it's repeated in some packages?

**Comment by turbomam** [comment]
@ramonawalls suggesting that
- `rel_to_oxygen` is about organisms
- `oxy_stat_samp` is about samples

Are we segregating these into core/packages appropriately

**Comment by mslarae13** [comment]
rel_to_oxygen specific to individual organism. Considering moving this out of MIxS. 
For NMDC & EMSL users likely to remove rel_to_oxygen as it's about a single organism & we're focusing on the biosample.

**Comment by ramonawalls** [comment]
We should probably get rid of re_to_oxygen, because it is organism biology and not specific to the sampling event. However, there are those who want to keep organism biology in MIxS. In this case, it might be important to keep it because if the organism is the sample, and its oxygen use is variable, you need to record that information.

Another possibility is that these are intended to be the same term, and having both of them is a mistake.

**Comment by turbomam** [comment]
```sql
select
	rel_to_oxygen,
	count(1)
from
	harmonized_wide hw
group by
	rel_to_oxygen
order by
	count(1);
```

|rel_to_oxygen|count(1)|
|-------------|--------|
||26421344|
|aerobe|39606|
|anaerobe|19525|
|missing|10136|
|not applicable|9321|
|NA|6336|
|facultative|5510|
|obligate anaerobe|2941|
|not collected|2757|
|microaerophilic|1495|
|NOT APPLICABLE|1249|
|Missing|1052|
|obligate aerobe|635|
|Not collected|499|
|microanaerobe|399|
|oxic|217|
|Not applicable|208|
|aerobic|198|
|Not Applicable|174|
|Aerobic|155|
|-|143|
|anaerobic|136|
|none|123|
|N/A|104|
|unknown|68|
|Unknown|50|
|Oxic|40|
|None|35|
|na|34|
|not available|25|
|facultative anaerobes|21|
|Not available|16|
|facultative anaerobic|15|
|facultative anaerobe|6|
|hypoxic|6|
|obligate aerobic|5|
|normal oxic seawater|4|
|oxic/anoxic boundary|4|
|22 mg/l|3|
|6.0-6.5 mg/l|3|
|Hypoxic|3|
|not provided|3|
|Aerobe|2|
|Anaerobe|2|
|obligate anaerobic|2|
|0 mg/l|1|
|1.0-2.2 mg/l|1|
|23.5 mg/l|1|
|25 mg/l|1|
|Aerob|1|
|Facultative|1|
|Urania control is 250-260 ÂµM, halocline samples 0-100ÂµM|1|
|aerobic-anaerobic|1|
|facultative aerobic|1|
|facultatively aerobic|1|
|obligate|1|

**Comment by turbomam** [comment]
```
select
	oxy_stat_samp,
	count(1)
from
	harmonized_wide hw
group by
	oxy_stat_samp
order by
	count(1) desc;
```

|oxy_stat_samp|count(1)|
|-------------|--------|
||26507498|
|NA|4204|
|aerobic|3559|
|anaerobic|2930|
|not applicable|1693|
|not collected|1669|
|missing|1664|
|anaerobe|535|
|NOT APPLICABLE|322|
|0,00|144|
|none|123|
|aerobe|36|
|Unknown|26|
|not collecte|24|
|Not collected|17|
|Not available|16|
|N/A|14|
|unknown|6|
|9,67|6|
|7,76|6|
|7,50|6|
|7,37|6|
|7,07|6|
|6,80|6|
|5,28|6|
|5,22|6|
|5,03|6|
|4,89|6|
|4,84|6|
|4,67|6|
|3,75|6|
|3,53|6|
|2,45|6|
|2,34|6|
|15,51|6|
|14,75|6|
|13,60|6|
|10,56|6|
|10,45|6|
|10,06|6|
|8.62|3|
|7,29|2|
|17,24|2|
|the sediment is anoxic but the water colum contains O2 (6.78-7.66 mg/L)|1|
|17,24 mg/L|1|

**Comment by ramonawalls** [comment]
Resolution: 

oxy_stat_samp is appropriate for some packages like soil, and it describes the (non-organismal) sample.

rel_to_oxygen can be used in certain checklists (e.g., MIGS, MIMARKS), but it is not mandatory in any of them. Just because something is in core, does not meet it has to be in everything (or even anything). 

We do not need to make changes to these terms, but we do need to improve how we communicate what core is, and we need to provide examples of valid and invalid usage of terms.
