### ISSUE TITLE
Difference in host_sex picklists

### ISSUE THREAD

**Issue by anjijohnston** [GenomicsStandardsConsortium/mixs#497]
We noticed differences in the picklists for host_sex in these env_packages:

[] For these packages:
Host_associated package
Human_associated package
Human-gut package
Human-oral
Human-skin
Human-vaginal

>Host_sex        [female|hermaphrodite|non-binary|male|transgender|transgender (female to male)|transgender (male to female)|undeclared]

[] For this package
Symbiont_associated package

>Host_sex        [female|hermaphrodite|male|neuter]

We will need the picklists to be the same - can you let me know if host_sex in the symbiont package should include the longer picklist?

**Comment by lschriml** [comment]
Hello Anji,
  yes, it should include the longer pick list.

Cheers,
Lynn

**Comment by ramonawalls** [comment]
The long list has been added as a string serialization, which resolves this issue. 

Discussions from today's CIG call:

It would be better to have the list as an enum, which could then be validated. 

To ensure compatibility with all formats, the parenthesis (round brackets) should be removed. Will removing them cause problems in dbs? 

There is a bigger issue that this term is confounding sex and gender. We should look to use an ontology for these values, such as https://www.ebi.ac.uk/ols4/ontologies/gsso. There have been some discussions with the urobiome groups about this issue. 

I will close this issue, since it is fixed, look for other issues about sex and gender, and open a new one if needed.
