### ISSUE TITLE
term request: plant struct

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#54]
Hello the Bioscales project is in need of the term:
plant struct

**Comment by cmungall** [comment]
Can you provide a definition?

**Comment by lschriml** [comment]
Thank you Bill.
 Can you suggest a definition, the MIXS package, and allowable values ?

Cheers,
Lynn

**Comment by wdduncan** [comment]
I have asked the bio-scales folks to comment on these tickets. I just submitted on their behalf.

**Comment by StantonMartin** [comment]
leaf endosphere
root endosphere
seed
flower
leaf surface
stem

**Comment by StantonMartin** [comment]
More comprehensive list coming soon. There should be tissue types similiar to what is in the human standard.

**Comment by StantonMartin** [comment]
This should go in the plant associated package

**Comment by wdduncan** [comment]
@StantonMartin 
> There should be tissue types similiar to what is in the human standard.  

Can you please clarify?   

Also, is the above list meant to be allowable values?

**Comment by StantonMartin** [comment]
correct, those are allowable values as examples. We will work on a more complete list of allowable values.

In humans, it looks like there is a separate package for human-associated, human-gut, human-oral, human-skin, human-vaginal.  We need something similiar for plants, which could be accomplished either in a package or in a series of structured comments.  I note that in humans, the idea of "gut" "oral" "skin"  and "vaginal" is referring to an organ. IN plants, there are two organ systems, a shoot system and a root system.  So it may be that we create a package called plant-shoots and another called plant-roots to be consistent with what was done in humans...

**Comment by only1chunts** [comment]
Hi,
Ideally, we require a definition of the term first. The syntax of the expected value and if appropriate the name of the ontology from which those values should be selected. In general, we try not to include long list of controlled vocabularies within the packages

**Comment by schadt** [comment]
So how do we resolve.  Would there need to be seperate standards for each like there is in the case of human microbiome samples. For human microbiome we have seperate standards for human oral, human vaginal, human gut/feces, human skin, etc.  so we would need separate similar plant version such as plant leaf endosphere, plant leaf phylosphere, plant stem, plant root endosphere, plant rhizoplane, plant rhizosphere, etc.?  Seems easier for me to have one plant standard with a controlled vocabulary for origin of the sample within each plant.

**Comment by only1chunts** [comment]
I am slightly confused here, are we talking about adding a new term to an existing package, or are you looking to create a new package with new terms, or a new package with existing terms? Perhaps a short explanation of the end goal might help?

The term "plant_struc" already exists, with the definition: "Name of plant structure the sample was obtained from; for Plant Ontology (PO) (v releases/2017-12-14) terms, see http://purl.bioontology.org/ontology/PO, e.g. petiole epidermis (PO_0000051). If an individual flower is sampled, the sex of it can be recorded here."

So the values you should use in that field are recommended to come from the PO. If you wish to be more specific to your users by allowing only a subset of those terms, then I would suggest that's a front end issue rather than making changes to the standard.

**Comment by schadt** [comment]
Sorry for the confusion and thanks for the specifics examples above. Looking at the PO terms this is very helpful and exactly what we are looking for. Is it available in the NMDC template? If so guess I must have missed this option in the version I was given to review.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lschriml** [comment]
This issue looks to be resolved based on previous comment.
