### ISSUE TITLE
Documentation, mixs directory, files 

### ISSUE THREAD

**Issue by lschriml** [GenomicsStandardsConsortium/mixs#704]
At the top level of mixs GitHub:
     to develop a .md documentation file to explain the upper level structure of the directory.

To explain the - end user directories and the developer directories. 

To document here the plan for devising this documentation.

**Comment by ramonawalls** [comment]
> At the top level of mixs GitHub: to develop a .md documentation file to explain the upper level structure of the directory.
> 
This file should be the existing readme.md file, which is what displays on the github repo landing page. 

> To explain the - end user directories and the developer directories.
> 

Since the focus is for end users (not developers) I suggest that it point to both our auto-generated documentation (which describes, terms, checklists, extension) as well as end-user documentation on our website (or static pages on the linkml generated documentation). We can use more traditional github and code-based documentation for the TWG. We can also include readme files in the github repo to help developers, who, after all, are still human and forget or have trouble finding things.

**Comment by turbomam** [comment]
I think this is a great issue and I appreciate @ramonawalls comment. But I think there are two or even three proposals at this point. I would like to start delivering  solution, but I want to be sure @sujaypatil96 and I know what the request is.
- additional readme type file?
- enhance existing `./README.md` by correcting statements about the filesystem and adding information about directories that are currently glossed-over
- using links within `./README.md` to link to other web resources, when the information about our directory structure would live?

**Comment by turbomam** [comment]
Also, how will we keep this in sync if/when new changes are made to the directory structure? Who would be responsible for that?
