### ISSUE TITLE
Include term title on full term table page

### ISSUE THREAD

**Issue by sujaypatil96** [GenomicsStandardsConsortium/mixs#729]
Request from @Woolly-at-EBI:

It's not fully clear what a particular term is from it's short _name_ as is presented/displayed on the _full term table_ page: https://genomicsstandardsconsortium.github.io/mixs/term_list/

Can we modify the page so as to include the term title in the table as well? Perhaps the title first, and then the shorthand underneath that wrapped in parentheses, like this:

<img width="810" alt="Screen Shot 2023-12-14 at 11 13 18 PM" src="https://github.com/GenomicsStandardsConsortium/mixs/assets/20239224/2dc01189-57c7-4e86-ad0b-81fbec7ff5df">

**Comment by turbomam** [comment]
This will likely make whatever columns are on the right now wrap off of the screen

@sujaypatil96 could implement this and leave it in his fork so we can see the current implementation in this repo and compare the two

**Comment by sujaypatil96** [comment]
@turbomam and I worked on this issue @Woolly-at-EBI 

Here's a preview of what adding the _title_ column to the full term table will look like if propagated upstream into the production mixs docs: https://sujaypatil96.github.io/mixs/term_list/

Keeping the user experience with respect to horizontal scrolling, use of real estate on page, etc. in mind do you think this will be a useful value addition to the MIxS docs?

**Comment by Woolly-at-EBI** [comment]
Great, yes I do think that adds more clarity and it is not a long scroll even now ( and personally I tend to search for terms anyway).
Admittedly, I am biased as our users are using the title rather than the short names. :-) It is definitely worth asking the Ramona/Chris/Lynn and at least one of the NCBI folk.

For some terms, just looking at the first handful, the title immediately adds clarity.
add_recov_method: secondary and tertiary recovery methods and start date
alt:  altitude    e.g. as my brain picks up things like Alanine aminotransferase for alt

**Comment by sujaypatil96** [comment]
Closed by PR #784
