### ISSUE TITLE
Expected value, Value syntax 

### ISSUE THREAD

**Issue by lschriml** [GenomicsStandardsConsortium/mixs#80]
**Current term details**
 Specifications to be made consistent across MIxS 

- When an ontology term is specified, to be used, in the definition.

- Issue, some terms have for Expected value 'text or', other only specify the ontology
  - I would rather we do not allow 'text' as an option, rather than using the specified ontology, 

**Expected value            Value syntax                                Example** 
 text or OBI      {text}|{termLabel} {[termID]}      

**update to:**                                                                         Example
OBI term, OBI ID                                                      time series design [EFO:EFO_0001779]

Note: the Value syntax varies across terms that use and ontology. 
--> I propose we unify this format to: 

{text} {termLabel}:{[termID]}

Cheers,
Lynn

as seen for terms: 

 experimental_factor
samp_mat_process 
growth facility

**Comment by mia-lgo** [comment]
Hello Lynn,

I joined the gensc-cig group back in November, so I might be missing some context here. Please correct me if I'm wrong.

Here, my humble opinion for the terms with expected value 'text or' :

In cases such as 'experimental_factor':  providing 'text or EFO and/or OBI' allows specifying the experiment when there is no single EFO or OBI term (even in combination) that applies. 

 - I am mentioning this because we've run into a similar situation with a submission we received in which adding the 'experimental_factor' field using 'text' proved to be the only way to understand the experimental setup and the relationship between the MIxS terms used.  

Leaving the option 'text or EFO and/or OBI' for non-mandatory MIxS fields (such as experimental_factor, samp_mat_process, etc.) allows (both researchers and curators) to provide details/context as 'text' when there is no appropriated ontology term(s). 

Perhaps specifying that an ontology term is _preferred_ over 'text' might help to encourage the use of EFO or OBI.

I hope I understood this right.

**Comment by mia-lgo** [comment]
Hi @lschriml let me know what are your thoughts.

**Comment by lschriml** [comment]
@mia-lgo - agreed, will leave the fields as is. 
In the definition, we do specify preference for using ontology terms.

Cheers,
Lynn
