### ISSUE TITLE
MIxS 5 urogenital disorder vs urine/urogenital tract disorder

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#85]
In MIxS 5, urogenital disorder has the definition:
```
History   of urogenitaltract disorders; can include multiple disorders
```
and  urine/urogenital tract disorder has the definition:
```
History   of urogenital disorders, can include multiple disorders
```
However, when I look these up on the internet both terms seem to be about the same thing. Does anyone know the difference between urogenital disorder and urogenital tract disorder?

cc @lschriml @cmungall @only1chunts @ramonawalls

**Comment by lschriml** [comment]
These are two distinct terms. 
   We can improve the definitions to clarify the distinction, and to align with other MIxS disease terms

Review notes:
 The genitourinary system, or urogenital system, are the organs of the reproductive system and the urinary system. In anatomy, the system is subdivided into tracts. The urogenital system - is divided into the urinary tract and the genital tract. 
 
Further review of other 'disorder' terms across the packages, I've noted below MIxS 'disorder' terms, where their definitions can be updated to point users to the associated disease terms. 

It would be correct to change the names of these terms to 'disease' rather than 'disorder', however, as these Package Item names have been in place for many years, I would instead just update the definition to provide more detailed guidance to users. 

 
I've made these updates in the MIxS 6 term updates google doc. 

Cheers,
Lynn 

NOTES: 

**In human vaginal package:**       
[row 397]
urogenit_disord
           urogenital disorder
           definition:  History of urogenital disorders, can include multiple disorders
  --> adding to the definition: 
     The terms should be chosen from the DO (Human Disease Ontology) at http://www.disease-ontology.org, reproductive system disease (https://disease-ontology.org/?id=DOID:15) or urinary system disease (https://disease-ontology.org/?id=DOID:18). 

**In human_associated package:**
[row 275]
urogenit_tract_disor 
                   urine/urogenital tract disorder   
                  definition:  History of urogenitaltract disorders; can include multiple disorders
   
      --> definition update, urogenital tract should be two words [DONE]
         Also, looking at the usage of this term, it has been used to record UTIs
   

[row 274]
kidney_disord
         urine/kidney disorder
         definition: History of kidney disorders; can include multiple disorders


[rows 266-268] 
        pulmonary_disord
                 lung/pulmonary disorder
                 definition: History of pulmonary disorders; can include multiple disorders
        nose_throat_disord
                 lung/nose-throat disorder
                 definition: History of nose-throat disorders; can include multiple disorders
        blood_blood_disord
                 blood/blood disorder
                 definition: History of blood disorders; can include multiple disorders

History of blood disorders; can include multiple disorders.  The terms should be chosen from the DO (Human Disease Ontology) at http://www.disease-ontology.org, hematopoietic system disease (https://disease-ontology.org/?id=DOID:74).

**human-gut package**
 [row 287]
gastrointest_disord
           gastrointestinal tract disorder
           definition: History of gastrointestinal tract disorders; can include multiple disorders 

[row 288]
liver_disord
      liver disorder
      definition: History of liver disorders; can include multiple disorders

**human-oral package** 
[row 321]
nose_mouth_teeth_throat_disord
         nose/mouth/teeth/throat disorder
         definition: History of nose/mouth/teeth/throat disorders; can include multiple disorders

**human-skin package**
[row 354]
dermatology_disord
          dermatology disorder
           definition: History of dermatology disorders; can include multiple disorders

**human vaginal package**
[row 396]
    gynecologic_disord
          gynecological disorder
          definition: History of gynecological disorders; can include multiple disorders

**Comment by lschriml** [comment]
Status: already updated in MIxS v6.0, 'MIxS6 packages - to edit'
